name: you_do
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  animated_line_through: ^1.0.4
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localization: ^0.2.0
  freezed: ^2.5.2
  go_router: ^13.2.2
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.3
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
